// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: file.proto

package server

import (
	"context"

	"github.com/cy77cc/hioshop/fileserver/rpc/internal/logic"
	"github.com/cy77cc/hioshop/fileserver/rpc/internal/svc"
	"github.com/cy77cc/hioshop/fileserver/rpc/pb"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 流式上传分片
func (s *FileServer) Upload(ctx context.Context, in *pb.UploadReq) (*pb.UploadResp, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *FileServer) CreateBucket(ctx context.Context, in *pb.CreateBucketReq) (*pb.CreateBucketResp, error) {
	l := logic.NewCreateBucketLogic(ctx, s.svcCtx)
	return l.CreateBucket(in)
}
