// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/cy77cc/hioshop_ms/application/fileserver/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 删除文件
				Method:  http.MethodDelete,
				Path:    "/api/file",
				Handler: deleteFileHandler(serverCtx),
			},
			{
				// 获取文件元数据
				Method:  http.MethodGet,
				Path:    "/api/file",
				Handler: getFileInfoHandler(serverCtx),
			},
			{
				// 文件下载
				Method:  http.MethodGet,
				Path:    "/api/file/download/:fileId",
				Handler: downloadFileHandler(serverCtx),
			},
			{
				// 文件上传
				Method:  http.MethodPost,
				Path:    "/api/file/upload",
				Handler: uploadFileHandler(serverCtx),
			},
			{
				// 文件列表（分页）
				Method:  http.MethodGet,
				Path:    "/api/files",
				Handler: getFileListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
