// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type UploadResp struct {
	Id          string `json:"id"`
	Url         string `json:"url"`
	Name        string `json:"name"`
	Size        int64  `json:"size"`
	ContentType string `json:"content_type"`
}
