// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUploadReq struct {
	Bucket string `json:"bucket"`
	Object string `json:"object"`
}

type CreateUploadResp struct {
	Bucket   string `json:"bucket"`
	Key      string `json:"key"`
	UploadID string `json:"uploadId"`
}

type UploadPartReq struct {
	UploadID   string `json:"uploadId"`
	PartNumber uint64 `json:"partNumber"`
	LastPart   bool   `json:"lastPart"`
}

type UploadPartResp struct {
	ETag       string `json:"eTag"`
	PartNumber string `json:"partNumber"`
}
