// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CompleteUploadReq struct {
	UploadId string `json:"uploadId"`
	Hash     string `json:"hash"`
}

type CompleteUploadResp struct {
	FileId  int64  `json:"fileId"`
	FileUrl string `json:"fileUrl"`
}

type InitUploadReq struct {
	Hash     string `json:"hash"`     // 文件hash，前端计算
	FileName string `json:"fileName"` // 原始文件名
	FileType string `json:"fileType"` // MIME 类型
	FileSize int64  `json:"fileSize"` // 文件大小
}

type InitUploadResp struct {
	UploadId string `json:"uploadId"`
	Bucket   string `json:"bucket"`
}

type UploadPartReq struct {
	UploadId   string `form:"uploadId"`
	PartNumber int    `form:"partNumber"`
	PartData   []byte `form:"partData"` // 实际分片数据（multipart）
}

type UploadPartResp struct {
	ETag string `json:"etag"`
}
