// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: file.proto

package server

import (
	"github.com/cy77cc/hioshop_ms/app/fileserver/rpc/internal/logic"
	"github.com/cy77cc/hioshop_ms/app/fileserver/rpc/internal/svc"
	"github.com/cy77cc/hioshop_ms/app/fileserver/rpc/pb"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

// 客户端流：客户端连续发送 UploadChunk，结束后服务端返回 UploadResponse
func (s *FileServer) Upload(stream pb.File_UploadServer) error {
	l := logic.NewUploadLogic(stream.Context(), s.svcCtx)
	return l.Upload(stream)
}
