// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // 是不是最后一段
	Bucket        string                 `protobuf:"bytes,6,opt,name=bucket,proto3" json:"bucket,omitempty"`
	PartNumber    uint64                 `protobuf:"varint,7,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"` // 0 是创建分片上传，1-10000 是上传分片
	Uid           uint64                 `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	UploadId      string                 `protobuf:"bytes,9,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileSize      int64                  `protobuf:"varint,10,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ContentType   string                 `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UploadReq) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *UploadReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadReq) GetPartNumber() uint64 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UploadReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"` // MinIO 返回的分片 ETag
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResp) Reset() {
	*x = UploadResp{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResp) ProtoMessage() {}

func (x *UploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResp.ProtoReflect.Descriptor instead.
func (*UploadResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResp) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UploadResp) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type CreateBucketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketReq) Reset() {
	*x = CreateBucketReq{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketReq) ProtoMessage() {}

func (x *CreateBucketReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketReq.ProtoReflect.Descriptor instead.
func (*CreateBucketReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBucketReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CreateBucketResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResp) Reset() {
	*x = CreateBucketResp{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResp) ProtoMessage() {}

func (x *CreateBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResp.ProtoReflect.Descriptor instead.
func (*CreateBucketResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBucketResp) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x04file\"\x91\x02\n" +
	"\tUploadReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\x12\x16\n" +
	"\x06bucket\x18\x06 \x01(\tR\x06bucket\x12\x1f\n" +
	"\vpart_number\x18\a \x01(\x04R\n" +
	"partNumber\x12\x10\n" +
	"\x03uid\x18\b \x01(\x04R\x03uid\x12\x1b\n" +
	"\tupload_id\x18\t \x01(\tR\buploadId\x12\x1b\n" +
	"\tfile_size\x18\n" +
	" \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\v \x01(\tR\vcontentType\"=\n" +
	"\n" +
	"UploadResp\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\")\n" +
	"\x0fCreateBucketReq\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\"*\n" +
	"\x10CreateBucketResp\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket2r\n" +
	"\x04File\x12+\n" +
	"\x06Upload\x12\x0f.file.UploadReq\x1a\x10.file.UploadResp\x12=\n" +
	"\fCreateBucket\x12\x15.file.CreateBucketReq\x1a\x16.file.CreateBucketRespB\x06Z\x04./pbb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_proto_goTypes = []any{
	(*UploadReq)(nil),        // 0: file.UploadReq
	(*UploadResp)(nil),       // 1: file.UploadResp
	(*CreateBucketReq)(nil),  // 2: file.CreateBucketReq
	(*CreateBucketResp)(nil), // 3: file.CreateBucketResp
}
var file_file_proto_depIdxs = []int32{
	0, // 0: file.File.Upload:input_type -> file.UploadReq
	2, // 1: file.File.CreateBucket:input_type -> file.CreateBucketReq
	1, // 2: file.File.Upload:output_type -> file.UploadResp
	3, // 3: file.File.CreateBucket:output_type -> file.CreateBucketResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
