// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: fileserver.proto

package fileservice

import (
	"context"

	"github.com/cy77cc/hioshop_ms/application/fileserver/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteFileRequest    = pb.DeleteFileRequest
	DeleteFileResponse   = pb.DeleteFileResponse
	DownloadFileRequest  = pb.DownloadFileRequest
	DownloadFileResponse = pb.DownloadFileResponse
	FileItem             = pb.FileItem
	GetFileInfoRequest   = pb.GetFileInfoRequest
	GetFileInfoResponse  = pb.GetFileInfoResponse
	ListFilesRequest     = pb.ListFilesRequest
	ListFilesResponse    = pb.ListFilesResponse
	UploadFileRequest    = pb.UploadFileRequest
	UploadFileResponse   = pb.UploadFileResponse

	FileService interface {
		// 上传文件
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
		// 下载文件
		DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error)
		// 获取文件信息
		GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*GetFileInfoResponse, error)
		// 删除文件
		DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
		// 列出用户文件列表
		ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

// 上传文件
func (m *defaultFileService) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

// 下载文件
func (m *defaultFileService) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.DownloadFile(ctx, in, opts...)
}

// 获取文件信息
func (m *defaultFileService) GetFileInfo(ctx context.Context, in *GetFileInfoRequest, opts ...grpc.CallOption) (*GetFileInfoResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetFileInfo(ctx, in, opts...)
}

// 删除文件
func (m *defaultFileService) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}

// 列出用户文件列表
func (m *defaultFileService) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.ListFiles(ctx, in, opts...)
}
