// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateUploadReq struct {
	Bucket      string `json:"bucket"`
	Key         string `json:"key"`
	Hash        string `json:"hash"`
	Size        int64  `json:"size"`
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
}

type CreateUploadResp struct {
	ETag     string `json:"eTag"`
	UploadID string `json:"uploadId"`
}

type UploadPartReq struct {
	UploadID   string `json:"uploadId"`
	PartNumber uint64 `json:"partNumber"`
	LastPart   bool   `json:"lastPart"`
}

type UploadPartResp struct {
	ETag       string `json:"eTag"`
	PartNumber string `json:"partNumber"`
}
