// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: fileserver.proto

package server

import (
	"context"

	"github.com/cy77cc/hioshop_ms/application/fileserver/rpc/internal/logic"
	"github.com/cy77cc/hioshop_ms/application/fileserver/rpc/internal/svc"
	"github.com/cy77cc/hioshop_ms/application/fileserver/rpc/pb"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *FileServiceServer) UploadFile(ctx context.Context, in *pb.UploadFileRequest) (*pb.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

// 下载文件
func (s *FileServiceServer) DownloadFile(ctx context.Context, in *pb.DownloadFileRequest) (*pb.DownloadFileResponse, error) {
	l := logic.NewDownloadFileLogic(ctx, s.svcCtx)
	return l.DownloadFile(in)
}

// 获取文件信息
func (s *FileServiceServer) GetFileInfo(ctx context.Context, in *pb.GetFileInfoRequest) (*pb.GetFileInfoResponse, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}

// 删除文件
func (s *FileServiceServer) DeleteFile(ctx context.Context, in *pb.DeleteFileRequest) (*pb.DeleteFileResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

// 列出用户文件列表
func (s *FileServiceServer) ListFiles(ctx context.Context, in *pb.ListFilesRequest) (*pb.ListFilesResponse, error) {
	l := logic.NewListFilesLogic(ctx, s.svcCtx)
	return l.ListFiles(in)
}
