// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type FileIDReq struct {
	Id int `json:"id"`
}

type FileInfo struct {
	FileId      string `json:"fileId"`
	FileName    string `json:"fileName"`
	Bucket      string `json:"bucket"`
	Size        int64  `json:"size"`
	ContentType string `json:"contentType"`
	Uploader    string `json:"uploader"`
	UploadTime  string `json:"uploadTime"`
}

type FileListReq struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type FileResp struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data FileInfo `json:"data"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UploadReq struct {
}

type UploadResp struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	FileId string `json:"fileId"`
	Url    string `json:"url"`
}
