// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileInfoFieldNames          = builder.RawFieldNames(&FileInfo{})
	fileInfoRows                = strings.Join(fileInfoFieldNames, ",")
	fileInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(fileInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(fileInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileInfoModel interface {
		Insert(ctx context.Context, data *FileInfo) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FileInfo, error)
		FindOneByFileId(ctx context.Context, fileId string) (*FileInfo, error)
		Update(ctx context.Context, data *FileInfo) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFileInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FileInfo struct {
		Id          uint64    `db:"id"`           // 主键ID
		FileId      string    `db:"file_id"`      // 文件唯一ID (UUID)
		FileName    string    `db:"file_name"`    // 原始文件名
		Bucket      string    `db:"bucket"`       // 存储桶
		ObjectName  string    `db:"object_name"`  // 存储路径/对象名
		Size        int64     `db:"size"`         // 文件大小（字节）
		ContentType string    `db:"content_type"` // 文件类型（MIME）
		Uploader    uint64    `db:"uploader"`     // 上传者用户ID
		UploadTime  time.Time `db:"upload_time"`  // 上传时间
		Hash        string    `db:"hash"`         // 文件哈希值
		Description string    `db:"description"`  // 文件描述
		DeletedTime time.Time `db:"deleted_time"` // 删除时间
		Status      int64     `db:"status"`       // 状态（1=正常，0=已删除）
	}
)

func newFileInfoModel(conn sqlx.SqlConn) *defaultFileInfoModel {
	return &defaultFileInfoModel{
		conn:  conn,
		table: "`file_info`",
	}
}

func (m *defaultFileInfoModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileInfoModel) FindOne(ctx context.Context, id uint64) (*FileInfo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileInfoRows, m.table)
	var resp FileInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileInfoModel) FindOneByFileId(ctx context.Context, fileId string) (*FileInfo, error) {
	var resp FileInfo
	query := fmt.Sprintf("select %s from %s where `file_id` = ? limit 1", fileInfoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, fileId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileInfoModel) Insert(ctx context.Context, data *FileInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, fileInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FileId, data.FileName, data.Bucket, data.ObjectName, data.Size, data.ContentType, data.Uploader, data.UploadTime, data.Hash, data.Description, data.DeletedTime, data.Status)
	return ret, err
}

func (m *defaultFileInfoModel) Update(ctx context.Context, newData *FileInfo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.FileId, newData.FileName, newData.Bucket, newData.ObjectName, newData.Size, newData.ContentType, newData.Uploader, newData.UploadTime, newData.Hash, newData.Description, newData.DeletedTime, newData.Status, newData.Id)
	return err
}

func (m *defaultFileInfoModel) tableName() string {
	return m.table
}
