// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	s3 "github.com/cy77cc/hioshop_ms/app/fileserver/api/internal/handler/s3"
	"github.com/cy77cc/hioshop_ms/app/fileserver/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 新建分段上传任务
				Method:  http.MethodPost,
				Path:    "/:bucket/:object",
				Handler: s3.CreateUploadHandler(serverCtx),
			},
			{
				// 新建分段上传任务
				Method:  http.MethodPut,
				Path:    "/:bucket/:object",
				Handler: s3.UploadPartHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/file-server/v1"),
	)
}
