// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"github.com/cy77cc/hioshop_ms/app/fileserver/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 文件上传
				Method:  http.MethodGet,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
			{
				// 文件上传完成
				Method:  http.MethodGet,
				Path:    "/upload/complete",
				Handler: CompleteUploadHandler(serverCtx),
			},
			{
				// 大文件上传初始化
				Method:  http.MethodPost,
				Path:    "/upload/init",
				Handler: InitUploadHandler(serverCtx),
			},
		},
	)
}
