// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	upload "github.com/cy77cc/hioshop_ms/app/fileserver/api/internal/handler/upload"
	"github.com/cy77cc/hioshop_ms/app/fileserver/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 完成上传，合并分片
				Method:  http.MethodGet,
				Path:    "/complete",
				Handler: upload.FileUploadCompleteHandler(serverCtx),
			},
			{
				// 初始化上传，生成 uploadId
				Method:  http.MethodGet,
				Path:    "/init",
				Handler: upload.FileUploadInitHandler(serverCtx),
			},
			{
				// 上传分片
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: upload.FileUploadPartHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
